export default {
  home: require('../assets/Images/homeIcon.png'),
  home2: require('../assets/Images/homeIcon2.png'),
  weather: require('../assets/Images/weather.png'),
  weather2: require('../assets/Images/weather2.png'),
  landIcon: require('../assets/Images/landIcon.png'),
  landIcon2: require('../assets/Images/landIcon2.png'),
  profileIcon: require('../assets/Images/profileIcon.png'),
  profileIcon2: require('../assets/Images/profileIcon2.png'),
  mandi: require('../assets/Images/mandi.png'),
  mandi2: require('../assets/Images/mandi2.png'),
  mic: require('../assets/Images/mic.png'),
  sms: require('../assets/Images/sms.png'),
  call: require('../assets/Images/call.png'),
  farmLogo: require('../assets/Images/farmbersLogo.png'),
  // pencil: require('../assets/Images/pencil.png'),
  googleLogo: require('../assets/Images/googleLogo.png'),
  fbLogo: require('../assets/Images/fbLogo.png'),
  dummy: require('../assets/Images/dummy.png'),
  profilePic: require('../assets/Images/profile_pic.png'),
  backIcon: require('../assets/Images/back.png'),
  bhindi: require('../assets/Images/bhindi.jpg'),
  caps: require('../assets/Images/caps.jpg'),
  farmbers: require('../assets/Images/farmbers.png'),
  tomata: require('../assets/Images/tomata.jpg'),
  refer: require('../assets/Images/Refer&eran.png'),
  bell: require('../assets/Images/BellIcon.png'),
  drawerImg: require('../assets/Images/drawerImg.png'),
  forward: require('../assets/Images/farward.png'),
  warning: require('../assets/Images/warning.png'),
  sun: require('../assets/Images/sun.png'),
  add: require('../assets/Images/add.png'),
  map: require('../assets/Images/map.png'),
  map1: require('../assets/Images/map1.jpg'),
  reffrSignup: require('../assets/Images/referSignup.png'),
  reffrSignup2: require('../assets/Images/reffrSignup2.png'),
  reffrRegistr: require('../assets/Images/reffrRegistr.png'),
  reffrRegistr2: require('../assets/Images/reffrRegistr2.png'),
  refferReward: require('../assets/Images/refferReward.png'),
  invitation: require('../assets/Images/invitation.png'),
  wallet: require('../assets/Images/wallet.png'),
  yes: require('../assets/Images/yes.png'),
  no: require('../assets/Images/no.png'),
  location: require('../assets/Images/location.png'),
  otp: require('../assets/Images/otp.png'),
  password: require('../assets/Images/password.png'),
  pincode: require('../assets/Images/pincode.png'),
  lock: require('../assets/Images/lock.png'),
  unlock: require('../assets/Images/unlock.png'),
  help: require('../assets/Images/help.png'),
  find: require('../assets/Images/find.png'),
  phone: require('../assets/Images/phone.png'),
  email: require('../assets/Images/email.png'),
  checklist: require('../assets/Images/checklist.png'),

  locationRed: require('../assets/Images/locationRed.png'),
  locationGrey: require('../assets/Images/locationGrey.png'),
  locationGreen: require('../assets/Images/locationGreen.png'),
  locationYellow: require('../assets/Images/locationYellow.png'),

  mandiPic: require('../assets/Images/mandiPic.jpg'),
  shopVeg: require('../assets/Images/shopVeg.jpg'),
  hotelKitchen: require('../assets/Images/hotelKitchen.jpg'),
  homeKit: require('../assets/Images/homeKit.jpg'),
  star: require('../assets/Images/star.png'),
  dot: require('../assets/Images/dot.png'),

  aboutUs: require('../assets/Images/Aboutus.png'),
  helpIcon: require('../assets/Images/Helpicon.png'),
  termsIcon: require('../assets/Images/termsIcon.png'),
  notificationIcon: require('../assets/Images/notificationIcon.png'),
  settingsIcon: require('../assets/Images/settingsIcon.png'),
  settingsIcon2: require('../assets/Images/settingsIcon2.png'),
  privacyIcon: require('../assets/Images/privacyIcon.png'),
  infoIcon: require('../assets/Images/info.png'),



};
